apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-app
  template:
    metadata:
      labels:
        app: simple-web-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-app
  namespace: devops
spec:
  selector:
    app: simple-web-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops