apiVersion: v1
kind: Namespace
metadata:
  name: todo-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-prod
  namespace: todo-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app-prod
  template:
    metadata:
      labels:
        app: todo-app-prod
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-prod
  namespace: todo-prod
spec:
  selector:
    app: todo-app-prod
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
